import { pgTable, serial, integer, text, boolean } from 'drizzle-orm/pg-core';

export const settings = pgTable('settings', {
  id: serial('id').primaryKey(),
  key: text('key').notNull().unique(),
  value: text('value'),
  type: text('type').default('text'),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const site_settings = pgTable('site_settings', {
  id: serial('id').primaryKey(),
  setting_key: text('setting_key').notNull().unique(),
  setting_value: text('setting_value'),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
  homepage_layout: text('homepage_layout'),
  site_header_layout: text('site_header_layout'),
  site_footer_layout: text('site_footer_layout'),
  homepage_type: text('homepage_type').default('normal'),
  default_category_id: integer('default_category_id'),
});

export const epaper_settings = pgTable('epaper_settings', {
  id: serial('id').primaryKey(),
  entries_per_page: integer('entries_per_page').default(12),
  include_header_footer_map: boolean('include_header_footer_map').default(false),
  include_header_footer_clip: boolean('include_header_footer_clip').default(false),
  default_publishing_status: text('default_publishing_status').default('publish-immediately'),
  disable_right_click: boolean('disable_right_click').default(false),
  keep_archive_days: integer('keep_archive_days').default(0),
  use_random_prefix: boolean('use_random_prefix').default(false),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const area_map_watermark_settings = pgTable('area_map_watermark_settings', {
  id: serial('id').primaryKey(),
  enable_watermarking: boolean('enable_watermarking').default(false),
  logo_url: text('logo_url'),
  logo_width_percentage: integer('logo_width_percentage').default(50),
  opacity: integer('opacity').default(100),
  mode: text('mode').default('in_outerside'),
  position: text('position').default('top_center'),
  min_width_px: integer('min_width_px').default(0),
  background_color: text('background_color').default('#ffffff'),
  foreground_color: text('foreground_color').default('#000000'),
  enable_border: boolean('enable_border').default(false),
  border_width: integer('border_width').default(2),
  border_color: text('border_color').default('#000000'),
  info_text: text('info_text'),
  info_text_font: text('info_text_font').default('English'),
  enable_center_watermark: boolean('enable_center_watermark').default(false),
  center_watermark_url: text('center_watermark_url'),
  center_watermark_opacity: integer('center_watermark_opacity').default(100),
  watermark_version: text('watermark_version'),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const category_watermark_settings = pgTable('category_watermark_settings', {
  id: serial('id').primaryKey(),
  category_id: integer('category_id').notNull().unique(),
  override_global_settings: boolean('override_global_settings').default(false),
  enable_watermarking: boolean('enable_watermarking').default(false),
  logo_url: text('logo_url'),
  logo_width_percentage: integer('logo_width_percentage').default(50),
  opacity: integer('opacity').default(100),
  mode: text('mode').default('in_outerside'),
  position: text('position').default('top_center'),
  min_width_px: integer('min_width_px').default(0),
  background_color: text('background_color').default('#ffffff'),
  foreground_color: text('foreground_color').default('#000000'),
  enable_border: boolean('enable_border').default(false),
  border_width: integer('border_width').default(2),
  border_color: text('border_color').default('#000000'),
  info_text: text('info_text'),
  info_text_font: text('info_text_font').default('English'),
  enable_center_watermark: boolean('enable_center_watermark').default(false),
  center_watermark_url: text('center_watermark_url'),
  center_watermark_opacity: integer('center_watermark_opacity').default(100),
  watermark_version: text('watermark_version'),
  clip_logo_url: text('clip_logo_url'),
  clip_brand_text: text('clip_brand_text'),
  clip_brand_name: text('clip_brand_name'),
  enable_clip_branding: boolean('enable_clip_branding').default(true),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});
